### ISSUE TITLE
System.ArgumentException: Value does not fall within the expected range. DTE2EventListener.cs:line 115

### ISSUE THREAD

**Issue by MuratTopcu** [LaggAt/ActivityWatchVS#1]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.3.10
- This extension: 1.0.15

### Description
Always gives the following error

System.ArgumentException:
System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at ActivityWatchVS.Listeners.DTE2EventListener.produceEvent(String caller) in C:\projects\activitywatchvs\ActivityWatchVS\Listeners\DTE2EventListener.cs:line 115

### Steps to recreate
1. Create Blazor App 3.0
2. Look Output Window

### Current behavior
It gives an error

### Expected behavior
No error

**Comment by bschwehn** [comment]
I also see this issue, basically always when not a code file is open, for example whenever I go the project properties. It is mildly annoying, as it can cause VS to switch the display in the output window from what I selected previously. 

Dirty fix is to simply remove the log call at https://github.com/LaggAt/ActivityWatchVS/blob/852493d7c68e8225fb380108d4836e7abfb2259f/ActivityWatchVS/Listeners/DTE2EventListener.cs#L154

**Comment by LaggAt** [comment]
fixed in v1.0.18 just deploying.

> Dirty fix is to simply remove the log call at

Right, but this would make it impossible to catch other errors there. I did only catch-and-ignore the ArgumentException there.
