### ISSUE TITLE
Install fails "extension/package.json not found inside zip" for VScodium

### ISSUE THREAD

**Issue by Hahlh** [LaggAt/ActivityWatchVS#3]
### Installed product versions
- Visual Studio and environment: 

<img width="275" alt="image" src="https://user-images.githubusercontent.com/45669613/89704499-6567c080-d954-11ea-9025-1b6def86a2ef.png">

- This extension: 1.0.18 and 1.1.27

### Description
I tried to find the extension through the marketplace with no luck. Also a manual install of both available version has failed both through the GUI and the CLI. 

The error it throws:
> extension/package.json not found inside zip.

Thank you for the dev work Florian!

**Comment by johan-bjareholt** [comment]
I think this extension is supposed to work for normal Visual Studio, not Visual Studio **Code** which is what VSCodium is based on.

Here's the Visual Studio Code extension, which recently got fixes for VSCodium
https://github.com/ActivityWatch/aw-watcher-vscode

**Comment by Hahlh** [comment]
Thanks for pointing that out Johan! 

Closing
